#define START_ROLE 1 //1 - attacker

#define OTLADKA 0

#define STOP_DRIBLER_SPEED 300
#define GRAB_DRIBLER_SPEED 350
#define DRIBLER_REVERSE_KICK_SPEED 250
#define DRIBLER_KICKING_SPEED 330

#define ROBOT_MAX_X 45
#define ROBOT_MIN_X -45

#define ROBOT_MAX_Y 210
#define ROBOT_MIN_Y 10

#define CENTRAL_GATE_OUT 55
#define SIDE_GATE_OUT 58

#define CHANGE_SPEED_VECTOR_CONST 2

#define USE_DRIBLER 1
#define USE_BLUETOOTH 0

#define TEST_DRIBLER 0

#define KP_GYRO_MOVING 1.0
#define KD_GYRO_MOVING 10.0
#define KI_GYRO_MOVING 0.01

#define KP_GYRO_STOPPED 1.0
#define KD_GYRO_STOPPED 10.0
#define KI_GYRO_STOPPED 0.01

#define BALL_DETECTION_LIGHTNESS 1500

#define BALL_K1
#define BALL_K2
#define BALL_K3
#define BALL_K4

#define KICK_OFF_DURATION 1000
